name: Docker Build, Push to AWS ECR & Terraform Setup

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  # Credential Setup
  credential-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

  # Install Terraform
  install-terraform:
    runs-on: ubuntu-latest
    needs: credential-setup
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

  # Terraform Setup
  terraform-setup:
    runs-on: ubuntu-latest
    needs: install-terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init -backend-config="bucket=project-devops-state-bucket" -backend-config="key=terraform.tfstate" -backend-config="region=ap-south-1"
        working-directory: ./infrastructure

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infrastructure

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Docker Works
  docker-works:
    runs-on: ubuntu-latest
    needs: terraform-setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build the Docker image
        run: docker build --build-arg MONGO_URI=${{ secrets.MONGO_URI }} -t project-devops -f ./app/Dockerfile ./app

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag the Docker image
        run: docker tag project-devops:latest 774305585645.dkr.ecr.ap-south-1.amazonaws.com/project-devops:latest

      - name: Push Docker image to ECR
        run: docker push 774305585645.dkr.ecr.ap-south-1.amazonaws.com/project-devops:latest

  # Kubernetes Deployments
  k8-deployments:
    runs-on: ubuntu-latest
    needs: docker-works
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key for EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem
          eval $(ssh-agent -s)
          ssh-add ec2-key.pem

      - name: Retrieve kubeconfig from EC2 Master
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@ec2-13-201-126-178.ap-south-1.compute.amazonaws.com "sudo cat /etc/kubernetes/admin.conf" > kubeconfig
          sed -i 's/172.31.41.132/ec2-13-201-126-178.ap-south-1.compute.amazonaws.com/' kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl get nodes --insecure-skip-tls-verify

      - name: Copy Kubernetes deployment files to EC2 Worker Node
        run: |
          scp -o StrictHostKeyChecking=no -i ec2-key.pem ./k8-deployments/deployment.yaml ubuntu@ec2-65-1-111-131.ap-south-1.compute.amazonaws.com:/home/ubuntu/k8-deployments/
          scp -o StrictHostKeyChecking=no -i ec2-key.pem ./k8-deployments/services.yaml ubuntu@ec2-65-1-111-131.ap-south-1.compute.amazonaws.com:/home/ubuntu/k8-deployments/

      - name: Install AWS CLI on Worker Node
        run: |
          ssh -o StrictHostKeyChecking=no -i "ec2-key.pem" ubuntu@ec2-65-1-111-131.ap-south-1.compute.amazonaws.com << 'EOF'
            sudo apt-get update
            sudo apt-get install -y awscli
            aws --version
          EOF

      - name: Create ECR Secret on Worker Node
        run: |
          ssh -o StrictHostKeyChecking=no -i "ec2-key.pem" ubuntu@ec2-65-1-111-131.ap-south-1.compute.amazonaws.com \
            "kubectl delete secret ecr-secret --ignore-not-found && \
             aws ecr get-login-password --region ap-south-1 | \
             kubectl create secret docker-registry ecr-secret \
             --docker-server=774305585645.dkr.ecr.ap-south-1.amazonaws.com \
             --docker-username=AWS \
             --docker-password=\$(cat) \
             --docker-email=your-email@example.com"

      - name: Deploy to Kubernetes on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@ec2-65-1-111-131.ap-south-1.compute.amazonaws.com << 'EOF'
            kubectl apply -f ./k8-deployments/deployment.yaml
            kubectl apply -f ./k8-deployments/services.yaml
          EOF
